package com.ottogo.weekly.api.models

import com.squareup.moshi.Json
import java.util.*

data class Plot(
    @Json(name = "starttime") val starttime: Date?,
    @Json(name = "endtime") val endtime: Date?,
    @Json(name = "name") val name: String,
    @Json(name = "id") val id: Int,
    @Json(name = "emoji") val emoji: String,
    @Json(name = "description") val description: String?,
    @Json(name = "group_id") val group_id: Int?,
    @Json(name = "relationship_id") val relationship_id: Int?,
    @Json(name = "autogenerated") val autogenerated: Boolean = false,
    @Json(name = "is_going") val is_going: Boolean = false,
    @Json(name = "invited") val invited: List<Profile>,
    @Json(name = "going") val going: List<Profile>,
    @Json(name = "not_going") val not_going: List<Profile>,
    @Json(name = "is_plot") val is_plot: Boolean = true,


    )
