package com.ottogo.weekly.viewmodels

import android.accounts.Account
import android.accounts.AccountManager
import android.accounts.AccountManagerCallback
import android.app.AlarmManager
import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.os.Build
import android.util.Log
import androidx.annotation.RequiresApi
import androidx.compose.runtime.*
import androidx.datastore.preferences.core.edit
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.ottogo.weekly.WEEKLY_COMPLETE_PREF_KEY
import com.ottogo.weekly.alarms.AlarmReceiver
import com.ottogo.weekly.api.WeeklyApi
import com.ottogo.weekly.api.models.*
import com.ottogo.weekly.dataStore
import kotlinx.coroutines.launch
import java.text.SimpleDateFormat
import java.util.*

@RequiresApi(Build.VERSION_CODES.N)
class UserViewModel: ViewModel() {


    var token by mutableStateOf<String?>(null)
    var profile by mutableStateOf<Profile?>(null)
    private val _friends = mutableStateMapOf<Int, Profile>()
    val friends: Map<Int, Profile>
        get() = _friends
    private val _chats = mutableStateListOf<Any>()
    val chats: List<Any>
        get() = _chats
    private val _groups = mutableStateMapOf<Int, Group>()
    val groups: Map<Int, Group>
        get() = _groups
    private val _calendars = mutableStateListOf<FriendCalendar>()
    private val _plots = mutableStateListOf<Plot>()
    val plots: List<Plot>
        get() = _plots
    private val _recommendations = mutableStateListOf<Plot>()
    val recommendations: List<Plot>
        get() = _recommendations
    private val _requests = mutableStateListOf<Profile>()
    val requests: List<Profile>
        get() = _requests




    @JvmName("setToken1")
    fun setToken(string: String){
        viewModelScope.launch {
            token = string
            getMain()

        }
    }

    fun addGroup(group: Group){
        _chats.add(0, group)
        _groups[group.id] = group
    }

    fun removeGroup(groupId: Int){
        _chats.removeIf {
            it is Group && it.id == groupId
        }
        _groups.remove(groupId)
    }

    fun removeCalendar(index: Int){
        _calendars.removeAt(index)
    }


    fun addCalendar(calendar: FriendCalendar){
        _calendars.add(calendar)
    }

    fun getMain(){
        viewModelScope.launch {
            val data = WeeklyApi.retrofitService.main(mapOf("Authorization" to "token $token"))
            Log.d("ViewModel", data.toString())
            clear()


            profile = data.profile

            for (friend in data.friends) {
                _friends[friend.user_id] = friend
                _chats.add(friend)
            }

            for (group in data.groups) {


                _groups[group.id] = group
                if (!group.autogenerated) {
                    _chats.add(group)
                }
            }
            print(_friends)

            print(_groups)

            _chats.sortByDescending {
                when (it) {
                    is Group -> it.messages.firstOrNull()?.timestamp ?: it.timestamp
                    is Profile -> it.messages.firstOrNull()?.timestamp ?: it.timestamp
                    else -> {
                        Date()
                    }
                }
            }

            _recommendations.addAll(data.recommendations)
            _requests.addAll(data.requests)

            _plots.addAll(data.plots)
        }

    }

    fun clear() {
        _friends.clear()
        _chats.clear()
        _requests.clear()
        _plots.clear()
        _groups.clear()
    }

    @RequiresApi(Build.VERSION_CODES.N)
    fun addPrivateMessage(message: ChatMessage){

        val recipientId: Int = if (message.recipient != profile?.user_id) {
            message.recipient!!
        } else {
            message.user_id
        }

        _chats.removeAll { it is Profile && it.user_id == recipientId }

        var temporaryProfile = _friends[recipientId]
        val messages = temporaryProfile?.messages?.toMutableList() ?: mutableListOf()
        messages.add(0, message)

        temporaryProfile = temporaryProfile?.copy(messages = messages.toList())
        _friends.remove(recipientId)
        _friends[recipientId] = temporaryProfile!!

        _chats.add(0, temporaryProfile!!)
    }

    fun inviteToPlot(plotId: Int, selectedIds: List<Int>){
        var tempPlot = _plots.first { it.id == plotId }
        val invitees = (tempPlot?.invited ?: listOf<Profile>()).toMutableList()
        for (id in selectedIds) {
            _friends[id]?.let { invitees.add(it) }
        }
        tempPlot = tempPlot?.copy(invited = invitees)
        _plots.removeIf { it.id == plotId }
        _plots.add(tempPlot)
    }

    fun inviteToGroup(groupId: Int, selectedIds: List<Int>){
        var tempGroup = _groups[groupId]
        val invitees = (tempGroup?.invited ?: listOf<Profile>()).toMutableList()
        for (id in selectedIds) {
            _friends[id]?.let { invitees.add(it) }
        }
        tempGroup = tempGroup?.copy(invited = invitees)
        _groups.put(groupId, tempGroup!!)
    }

    fun updateGroup(groupId: Int, group: Group){

        _groups.put(groupId, group)
    }

    @RequiresApi(Build.VERSION_CODES.N)
    fun removeFriend(userId: Int){
        _chats.removeIf {
            it is Profile && it.user_id == userId
        }
        _friends.remove(userId)
    }

    @RequiresApi(Build.VERSION_CODES.N)
    fun removeRequest(userId: Int){
        _requests.removeIf {
            it is Profile && it.user_id == userId
        }
    }

    fun addFriend(profile: Profile){
        _chats.add(0, profile)
        _friends[profile.user_id] = profile
    }

    private var alarmMgr: AlarmManager? = null
    private lateinit var alarmIntent: PendingIntent

    fun addPlot(plot: Plot, context: Context? = null){

        if (context != null && plot.starttime != null && plot.is_plot) {
            alarmMgr = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
            alarmIntent = Intent(context, AlarmReceiver::class.java).let { intent ->
                intent.putExtra("plot", plot.name + " " + plot.emoji)
                val sdf = SimpleDateFormat("EEE MMM dd HH:mm:ss z yyyy").format(plot.starttime)
                intent.putExtra("starttime", sdf)
                PendingIntent.getBroadcast(context, 0, intent, PendingIntent.FLAG_IMMUTABLE)
            }


            val eightTheDayBefore: Calendar = Calendar.getInstance()
            eightTheDayBefore.time = plot.starttime
            eightTheDayBefore.add(Calendar.DATE, -1)
            eightTheDayBefore.set(Calendar.HOUR_OF_DAY, 20)
            val twoHoursBefore: Calendar = Calendar.getInstance().apply {
                timeInMillis = System.currentTimeMillis()
                set(Calendar.HOUR_OF_DAY, 23)
                set(Calendar.MINUTE, 50)
            }
            twoHoursBefore.time = plot.starttime
            twoHoursBefore.add(Calendar.HOUR_OF_DAY, -2)

            alarmMgr?.setExact(
                AlarmManager.RTC_WAKEUP,
                eightTheDayBefore.timeInMillis,
                alarmIntent
            )

            alarmMgr?.setExact(
                AlarmManager.RTC_WAKEUP,
                twoHoursBefore.timeInMillis,
                alarmIntent
            )
        }

        _plots.add(plot)
    }

    @RequiresApi(Build.VERSION_CODES.N)
    fun addGroupMessage(message: ChatMessage){

        _chats.removeAll { it is Group && it.id == message.group }

        val temporaryGroup = _groups[message.group]
        val messages = temporaryGroup?.messages?.toMutableList() ?: mutableListOf()
        messages.add(0, message)

        temporaryGroup?.messages = messages.toList()
        _groups.remove(message.group)
        _groups[message.group!!] = temporaryGroup!!

        _chats.add(0, temporaryGroup!!)
    }

    

    fun addMessage(message: ChatMessage){
        if (message.recipient != null) {

            addPrivateMessage(message = message)
        } else {
            addGroupMessage(message = message)
        }

    }


    suspend fun acceptPlotInvite(plot: Plot){

        WeeklyApi.retrofitService.acceptPlotInvitation(mapOf("Authorization" to "token ${token}"), plot.id)
        _plots.remove(plot)
        var newInvitedList = plot.invited
        var newGoingList = plot.going
        newInvitedList.toMutableList().removeIf { it.user_id == profile?.user_id }
        profile?.let { newGoingList.toMutableList().add(it) }

        _plots.add(plot.copy(is_going = true, invited = newInvitedList, going = newGoingList))

    }

    suspend fun rejectPlotInvite(plot: Plot){
        WeeklyApi.retrofitService.rejectPlotInvitation(mapOf("Authorization" to "token ${token}"), plot.id)
        _plots.remove(plot)

    }

    suspend fun interestedPlotInvite(plot: Plot){
        WeeklyApi.retrofitService.interestedPlotInvitation(mapOf("Authorization" to "token ${token}"), plot.id)
        _recommendations.remove(plot)

    }

    fun removePlot(plotId: Int){
        _plots.removeAll { it.id == plotId }

    }

    fun updatePlot(plotId: Int, plot: Plot){
        _plots[_plots.indexOfFirst { plotId == it.id }] = plot
    }

    fun addCalendarAvailabilities(selectedCalendar: Int, availabilities: List<Availability>) {
        val newCalendar = _calendars[selectedCalendar].copy(availabilities = availabilities)
        _calendars[selectedCalendar] = newCalendar
    }

    fun seenChatMessages(userId: Int? = null, groupId: Int? = null){
        if (userId != null) {
            _chats.replaceAll {
                if (it is Profile && it.user_id == userId){
                    val messages = it.messages.toMutableList()
                    messages.replaceAll { it.copy(seen = true) }
                    it.copy(messages = messages)
                }
                else {
                    it
                }
            }
        } else {
            _chats.replaceAll {
                if (it is Group && it.id == groupId){
                    val messages = it.messages.toMutableList()
                    messages.replaceAll { it.copy(seen = true) }
                    it.copy(messages = messages)
                }
                else {
                    it
                }
            }
        }
    }

    val ACCOUNT_TYPE = "com.ottogo.weekly"

    fun getToken(context: Context) {
        val accountManager = AccountManager.get(context)
        try {


            val account = accountManager.getAccountsByType(ACCOUNT_TYPE)[0]

            accountManager.getAuthToken(account, ACCOUNT_TYPE, null, false, AccountManagerCallback {
                //val token = it.getResult()
//                    token = token
                Log.d("tokenGet", it.getResult().toString())
                Log.d("tokenGet", account.toString())
                Log.d("tokenGet", it.isDone.toString())
                token = it.getResult().get("authtoken") as String



            }, null)


        } catch (ignored: Exception) {
            Log.d("tokenGet", ignored.toString())


        }




    }

    suspend fun updateWeeklyCompletePref(context: Context){
        context.dataStore.edit { settings ->
            val currentCounterValue = settings[WEEKLY_COMPLETE_PREF_KEY] ?: 0
            settings[WEEKLY_COMPLETE_PREF_KEY] = SimpleDateFormat("dd-MM-yyyy").format(Date())

        }
    }

    fun setToken(username: String, token: String, context: Context){
        Log.d("tokenSet", token)
        val accountManager = AccountManager.get(context)
        val account = Account(username, ACCOUNT_TYPE)
        accountManager.addAccountExplicitly(account, "", null);
        accountManager.setAuthToken(account, ACCOUNT_TYPE, token)
        this.token = token
        viewModelScope.launch {
            getMain()
        }
    }

    fun logout(context: Context){
        val accountManager = AccountManager.get(context)
        val account = accountManager.getAccountsByType(ACCOUNT_TYPE)[0]
        accountManager.removeAccount(account, AccountManagerCallback {
            profile = null
            _friends.clear()
            _chats.clear()
            _groups.clear()
            _recommendations.clear()
            _plots.clear()
            _requests.clear()
            token = null

        }, null)

    }

}


