package com.ottogo.weekly.ui.calendar.plot

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.navigation.NavController
import com.ottogo.weekly.R
import com.ottogo.weekly.api.models.Plot
import com.ottogo.weekly.api.models.Profile
import com.ottogo.weekly.ui.calendar.ui.components.EmojiCircle
import com.ottogo.weekly.ui.calendar.ui.components.PlotItem
import com.ottogo.weekly.ui.components.CustomButton
import com.ottogo.weekly.ui.components.TitleBar
import com.ottogo.weekly.ui.login.coloredShadow
import com.ottogo.weekly.ui.theme.ExtendedTheme
import com.ottogo.weekly.viewmodels.UserViewModel
import java.text.SimpleDateFormat

@Composable
fun RecommendedPlotsPage(navController: NavController, userViewModel: UserViewModel) {


    Column () {
        TitleBar(navController = navController, title = "Plans")

        Column(Modifier
            .verticalScroll(rememberScrollState())) {
            userViewModel.recommendations.forEach{
                RecommendedPlotItem(plot = it, userViewModel = userViewModel) {
                    navController.navigate("plotPage/${it.id}")
                }
            }

            Spacer(Modifier.height(24.dp))

            CustomButton(buttonText = "Feedback", onClick = { navController.navigate("feedbackPage") }, backgroundColor = ExtendedTheme.colors.LightGray, textColor = ExtendedTheme.colors.Black60, modifier = Modifier.padding(horizontal = 16.dp))
        }
    }
}

@Composable
fun RecommendedPlotItem(plot: Plot, userViewModel: UserViewModel, onClick: () -> Unit) {
    val date = if (plot.starttime != null){
        SimpleDateFormat("EEEE, MMM d").format(plot.starttime)

    } else {
        ""
    }
    val time = if (plot.starttime != null){
        SimpleDateFormat("h:mma").format(plot.starttime)

    } else {
        "Date undecided"
    }

    val invitees = if (userViewModel.groups[plot.group_id]?.autogenerated == false) { userViewModel.groups[plot.group_id]?.name ?: "" } else { plot.invited.joinToString (separator = ", "){ "${if (it.name.contains(" ")) { it.name.split(" ")[0] } else { it.name } }" }}

    Column() {

        Spacer(modifier = Modifier.height(16.dp))

        Text(date, style = MaterialTheme.typography.h5,
            color = ExtendedTheme.colors.Black40, modifier = Modifier.padding(horizontal = 16.dp))

        Column(
            Modifier
                .fillMaxWidth()
                .padding(16.dp)
                .coloredShadow(
                    color = Color(0xFFB3B3B3),
                    alpha = .2F,
                    offsetX = 3.dp,
                    offsetY = 5.dp
                )
                .clip(RoundedCornerShape(12.dp))
                .clickable {
                    onClick()
                }
                .background(MaterialTheme.colors.background)) {
            Row(verticalAlignment = Alignment.CenterVertically, modifier = Modifier.padding(horizontal = 16.dp, vertical = 24.dp)) {

                EmojiCircle(emoji = plot.emoji)

                Spacer(modifier = Modifier.width(16.dp))

                Column() {
                    Text(plot.name + " with " + invitees, style = MaterialTheme.typography.h3, overflow = TextOverflow.Ellipsis, maxLines = 1)
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(time, style = MaterialTheme.typography.body2,
                        color = ExtendedTheme.colors.Black60)
                    Spacer(modifier = Modifier.height(8.dp))
                    Text("Tap to edit/see more", style = MaterialTheme.typography.h5, color = MaterialTheme.colors.primary)

                }
            }
            Divider(thickness = 1.dp, color = ExtendedTheme.colors.LightGray)

              Text("Are you in?", style = MaterialTheme.typography.h5, color = ExtendedTheme.colors.Black60, modifier = Modifier.padding(16.dp))

                Row(
                    Modifier
                        .fillMaxWidth()
                        .padding(horizontal = 16.dp)
                        .padding(bottom = 16.dp)) {
                    CustomButton(buttonText = "I'm out", textColor = ExtendedTheme.colors.Black60, backgroundColor = ExtendedTheme.colors.LightGray, onClick = { userViewModel.rejectPlotInvite(plot) }, modifier = Modifier.weight(1F))
                    Spacer(modifier = Modifier.width(16.dp))
                    CustomButton(buttonText = "I'm in!", onClick = { userViewModel.interestedPlotInvite(plot) }, modifier = Modifier.weight(1F))

                }
            }



    }
}